### ISSUE TITLE
Interval type allows for impossible intervals

### ISSUE THREAD

**Issue by duncanmalashock** [battermann/Tonal#11]
According to theory, intervals can either be "perfect" or "imperfect". Either type can be augmented or diminished, but only perfect intervals can be perfect, and only imperfect intervals can be either major or minor.

Currently the `Interval` type allows for impossible interval types like `Minor Octave` or `Perfect Third`, which can't really occur practically.

In my previous implementation I restricted invalid qualities by modeling `PerfectQuality` and `ImperfectQuality` types: [implementation here](https://github.com/duncanmalashock/elm-music-theory/blob/master/src/Interval.elm). We could do similarly here.

Is this a big issue? I don't know whether I have much of an opinion. On principle, I think it might be a good idea to use here if modeling the domain accurately is of high value to us. But on the other hand, if we make `Interval` an opaque type with named constructor functions and don't expose `IntervalName` or `IntervalQuality`, this will remain an implementation detail that client code never has to deal with.

But if we end up writing code that operates on intervals (for example, adding intervals together), then modeling intervals more accurately may help us prevent bugs.

**Comment by battermann** [comment]
Yeah, I'm aware of this.

It's implemented as an opaque type. The only available constructors are constants to create valid intervals. I'm a big fan "make invalid state impossible". So for a consumer it's impossible to create invalid intervals, right now.

Maybe let's keep this in mind. In case we get to a point where we have to change the internals of `Interval` we can revisit, and reevaluate this issue?
