### ISSUE TITLE
PitchClass: Standardize on PitchClass type

### ISSUE THREAD

**Issue by duncanmalashock** [battermann/Tonal#8]
I would expect public-facing functions like `toString`, `asNaturalOrRaisedOnce`, `asNaturalOrLoweredOnce`, and `exact` to take `PitchClass`es as arguments and return values. I can see how tuple conversion might be convenient for client code, but mixing those types seems to create an API that's more difficult to work with than it needs to be.

I'd recommend implementing `fromTuple` and `toTuple`, and have all the rest of the public API for `PitchClass` use `PitchClass`es in their function signatures.

**Comment by battermann** [comment]
There is a certain reasoning behind this. I'll try to explain later. Just briefly, your point is valid. I think there are two different concerns mixed together is this module: working with pitch classes and enharmonic spelling. Maybe the latter should be in it's own module: `PitchClass.EnharmonicSpelling`.

**Comment by duncanmalashock** [comment]
I like that idea.

I also think it would be helpful for us each to see examples of how we'd like to be able to use this package's API, that we could point to in these situations, so we can see the other person's goals a little more concretely. Some folks do this with an `examples` directory next to `src`.
